FROM node:20-slim
LABEL maintainer="hello@wagtail.org"

RUN apt-get update && apt-get install rsync make -y
COPY ./wagtail/package.json ./wagtail/package-lock.json ./

RUN npm config set registry https://registry.npm.taobao.org/
RUN npm --prefix / install --loglevel info
